### ISSUE TITLE
Hourly and daily entities showing impossible temps.

### ISSUE THREAD

**Issue by chrisfromthelc** [Pirate-Weather/pirate-weather-ha#135]
![Screen Shot 2023-08-29 at 10 10 35 AM](https://github.com/alexander0042/pirate-weather-ha/assets/8002138/a6c8d6cd-bdd2-4d1f-9182-b92c1991e182)

![Screen Shot 2023-08-29 at 10 14 16 AM](https://github.com/alexander0042/pirate-weather-ha/assets/8002138/531ebaac-ed2e-4c9f-af4a-0df63bf57c5f)

It seems to have happened overnight; I've been on the same (current) version as of a week or so now and the temps have worked fine until this morning.

**Comment by chrisfromthelc** [comment]
It seems like this may have been from the API being unavailable during when it was called for an update (indicated by the logs). A quick restart cleared it up, but there might be a better way to handle this on API non-availability. Perhaps just not updating and showing an error instead?

**Comment by kbarnes3** [comment]
I've seen similarly large temps and I use Fahrenheit as well. I noticed that if I did the C->F conversion on the temperature in F, I would get the value displayed in Pirate Weather. For example, if it was 70 F outside, I would see values of 158 F in the UI, which would be the correct value if it was 70 C. Maybe there are conditions where the temperatures can get double converted?

**Comment by angrycatmeowmeow** [comment]
I just set mine up and I'm seeing the same. Setting units to C makes it show the actual temperature in F. I set the units to US when I configured the integration so I'm not sure why it's acting like the temp it's getting is in C then converting it to F.

**Comment by alexander0042** [comment]
Apologies for missing this- I was focused on some API changes, so just catching up now. 

This is a pretty strange problem, and I'm wondering if you've noticed it again since this? The "units" on the configuration screen are only used for the sensors, since the coordinator entity should always be getting the data from the API in SI units, with HA doing the rest of the conversion? If it seems related to the downtime, maybe HA is doing something to try to guess the correct unit and getting it incorrect? 

I pushed out v1.3 this morning as a pre-release, which switches to the new HA system for weather forecasts. Let me know if you have a chance to update to this, since I'm thinking it might help here.

**Comment by cloneofghosts** [comment]
Stable version of 1.3 has been released. Hopefully it helps with this issue but if it happens again feel free to reply.

**Comment by cloneofghosts** [comment]
Haven't heard anything on this issue in over a month so I'm going to close it for now. If it pops up again feel free to re-open or create a new issue.
