### ISSUE TITLE
Incorrect Temperature

### ISSUE THREAD

**Issue by t34wrj** [Pirate-Weather/pirate-weather-ha#213]
### Describe the bug

My latitude and longitude are entered correctly but the current temperature is incorrect. It is now currently 18 degrees celsius according to numerous weather sources but PirateWeather is reporting the temperature as 15.7 degrees celsius which is incorrect.

### Expected behavior

For the temperature to be correct.

### Actual behavior

An incorrect temperature is shown.

### Home Assistant version

2024.4.2

### Integration version

1.4.5.1

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/), [parameter documentation](https://web.archive.org/web/20230128172320/https://www.home-assistant.io/integrations/weather.darksky/) and [sensor documentation](https://web.archive.org/web/20230326100953/https://www.home-assistant.io/integrations/darksky) before opening this issue.
- [X] I have searched this repository and [Pirate Weather Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have checked to see if the issue is not an API issue.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
Hi, thanks for using this service, and apologies for the issue here. Do you mind sharing your approximate location, since that will help me dial in the issue

**Comment by t34wrj** [comment]
Hey - thanks for putting the service together. I'm in the South of England. Having enabled the apparent temperature sensors, these seem to give a more consistent temperature compared to the other weather services.

**Comment by alexander0042** [comment]
Thanks for the info! The apparent temperature might line up closer to what other sources say, since they often default to that. The other possibility is depending on how close to the ocean you area, it'll sometimes be swayed by that, but only if you're within a couple km

**Comment by t34wrj** [comment]
No worries. As an aside, can I ask what the difference is between the 0h and the 'normal' sensor. For example, my sensor.pirateweather_wind_speed sensor states 11.03mph but the sensor.pirateweather_wind_speed_0h states 10.25mph? Thanks for your help.

**Comment by alexander0042** [comment]
Good question, and something I should improve in the docs. 0h is the top of the hour, while the other sensor is the current condition. Behind the scenes it's just a linear interpolation, between hours 0 and 1, so you should see values between those two numbers

**Comment by RollingStar** [comment]
I might be running into this. Since I updated my Hass and all associated addons (PirateWeather) a few days ago it seems like the weather is out of sync with PW's hourly forecast. rn it's showing 66F which isn't supposed to happen for 3 hours. I think this is my first time Hass has been on PW 2.x but I'm not sure.

![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/4810902/7954c530-a9c1-42ef-b25f-5b9435f1c923)

![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/4810902/b0c3bfa2-af68-4032-9528-64289093e4f4)

This is weather.com which generally feels right to me:

![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/4810902/76b76ab2-15cc-49c0-9026-03d37fc48187)

My ecobee thermostat shows 70F from whatever cloud service it's pulling from.

I have PW updating every 15 minutes. I would expect the current temperature to be between the current hour's forecasted temp and the next hour's forecasted temp. (Fun wrinkle: I think my PW hourly forecast and some other info do not update in lockstep, so for example it will show 10pm on the hourly forecast when it's 11:06. But nothing in my data should be older than 15 minutes.)

**Comment by cloneofghosts** [comment]
The reason why you're seeing the current temperature below the forecasted hourly temperature is due to the fact that the current temp and the hourly temp come from different models. The current temp is coming from HRRR whereas the hourly temp is coming from NBM.

This is something that @alexander0042 should improve in the docs as they haven't fully been updated for version 2.0.
