### ISSUE TITLE
possibility to extend to myradar api?

### ISSUE THREAD

**Issue by skyw33** [Pirate-Weather/pirate-weather-ha#84]
The myradar api claims to be a "drop-in replacement" of the dark sky api format (with a free tier).  Assuming it's easy to do, would you be willing to extend the integration to accept a myradar api key?  https://myradar.dev/apis

**Comment by Nixon506E** [comment]
Feel free to give this a shot for myRadar support:
https://github.com/Nixon506E/myradar-ha

**Comment by cloneofghosts** [comment]
I had forked this repository and was looking into setting up an integration for this but I found out the API isn't free. From the looks of things the cheapest option is $199/month.

There is a 60 day free trial where I could get it setup and make sure it works. I won't be something I'd be able to work on long-term due to the cost of the API and I wouldn't be able to test to make sure it works after the trial is over.

You should be able to replace the API URL with the one from MyRadar but they could have made other changes to the API so it may not work. I'll leave this open but remove the keep label.
